### ISSUE TITLE
Error in working of tool

### ISSUE THREAD

**Issue by KerinPithawala** [ritikaxx/Stega-Steganography-Tool#1]
While uploading image/audio/video, I am getting error FileNotFoundError.
![image](https://user-images.githubusercontent.com/46436993/151497369-b7a03f17-b2c6-47c3-a86d-eaf8a4735ea8.png)

**Comment by ritikaxx** [comment]
Make sure to add a static folder in each of Text, Audio , Image and Video folder in the modes folder.This is where your uploaded media will be saved.
